// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnuaxInQMDeuFdQedOGoZbZnkIgUX7sew',
    appId: '1:184866803626:android:86267bc89a20e243cb65d3',
    messagingSenderId: '184866803626',
    projectId: 'student-mentorship',
    storageBucket: 'student-mentorship.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqUIHoKW_W8j21i3CHkrZbc6wzsUeL7dE',
    appId: '1:184866803626:web:3eb7301fc713c085cb65d3',
    messagingSenderId: '184866803626',
    projectId: 'student-mentorship',
    authDomain: 'student-mentorship.firebaseapp.com',
    storageBucket: 'student-mentorship.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK5g2L9vfrrvbV-OVnqVbGc1co1QsyN8M',
    appId: '1:184866803626:ios:079630ab7c9ff682cb65d3',
    messagingSenderId: '184866803626',
    projectId: 'student-mentorship',
    storageBucket: 'student-mentorship.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK5g2L9vfrrvbV-OVnqVbGc1co1QsyN8M',
    appId: '1:184866803626:ios:079630ab7c9ff682cb65d3',
    messagingSenderId: '184866803626',
    projectId: 'student-mentorship',
    storageBucket: 'student-mentorship.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqUIHoKW_W8j21i3CHkrZbc6wzsUeL7dE',
    appId: '1:184866803626:web:5f869a4cb510b4aecb65d3',
    messagingSenderId: '184866803626',
    projectId: 'student-mentorship',
    authDomain: 'student-mentorship.firebaseapp.com',
    storageBucket: 'student-mentorship.firebasestorage.app',
  );

}